# -*- coding: utf-8 -*-
"""Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8AOv1AZZhfxXXYyYDm3bTolxdI3niK-
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import drive
drive.mount('/gdrive')

import os
os.chdir("/gdrive/My Drive")
df = pd.read_csv("stco1039.csv" ,parse_dates=[1])
df = df.drop(columns=['stco'])
df.dtypes



# !ls

df.head()
# df.rename(columns={" Year": "Y", 'corn ': 'corn', 'soybean ':"soya"})#, 'cotton ', 'wheat ', 'ppt1 ', 'ppt2'""})

df.tail()

df['year'] = pd.to_datetime(df.year , format = '%d/%m/%Y %H.%M.%S')
# df.set_index('', inplace = True) 
data = df.drop(['year'], axis=1)
data.index = df.year
data.head()

df.columns
data.columns

column = data.columns
for a in column:
    for b in range(0,len(data)):
       if data[a][b] == -200:
           data[a][b] = data[a][b-1]

train = data[:int(0.8*(len(data)))]
valid = data[int(0.8*(len(data))):]

from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()

prediction = model_fit.forecast(model_fit.y, steps=len(valid))

prediction

import math
from sklearn.metrics import mean_squared_error

pred = pd.DataFrame(index=range(0,len(prediction)),columns=data.columns)
for b in range(0,6):
    for a in range(0, len(prediction)):
       pred.iloc[a][b] = prediction[a][b]

for i in data.columns:
    print('rmse value for', i, 'is : ', math.sqrt(mean_squared_error(pred[i], copy[i])))

copy = valid.copy()
# copy.head()
copy = copy.reset_index(drop=True)
print(copy.head())

print(valid.head())
pred.head()